### ISSUE TITLE
0 feature count?

### ISSUE THREAD

**Issue by trietmnj** [HydrologicEngineeringCenter/go-coastal#2]
Fc is 0, so the for loop to do the calculation wouldn't be triggered. Fc should be 2, I subsetted the data with a linux based tool called ogr2ogr, but it looks like it's read in correctly.

![image](https://user-images.githubusercontent.com/53122983/141011997-2be0a69f-112d-44c0-b675-283acd29757d.png)

![image](https://user-images.githubusercontent.com/53122983/141012458-7c3ce983-8ce2-4d89-b5ab-ffde5507417a.png)

**Comment by HenryGeorgist** [comment]
the two structures you selected from the NSI randomly using OGR2OGR are not in the bounding box of the hydraulic event provider, which means that the bounding box filter in the setspatialfilterrect is excluding the two features from the feature count.

choose a structure in the bounding box for testing, and you will get a feature count of 1 (or greater depending on how many features you select to keep)
